-- Library Management schema + constraints + indexes + RLS policies
-- Apply with: supabase db reset (local) or supabase db push (remote)

create extension if not exists pgcrypto;

-- ----------
-- Tables
-- ----------

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('Admin', 'Librarian', 'Patron')),
  created_at timestamptz not null default now()
);

create table if not exists public.biblios (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  isbn text,
  description text,
  cover_url text,
  publisher text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint biblios_isbn_unique unique (isbn)
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  biblio_id bigint not null references public.biblios(id) on delete cascade,
  barcode text,
  status text not null default 'available' check (status in ('available', 'checked_out', 'reserved', 'lost', 'damaged')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint items_barcode_unique unique (barcode)
);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  biblio_id bigint not null references public.biblios(id) on delete restrict,
  borrowed_at timestamptz not null default now(),
  due_date timestamptz not null,
  renewals_used integer not null default 0 check (renewals_used >= 0),
  status text not null check (status in ('CheckedOut', 'Returned', 'Overdue')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  status text not null check (status in ('Unpaid', 'Paid', 'Waived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.holds (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  biblio_id bigint not null references public.biblios(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'ready', 'completed', 'cancelled', 'expired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.engagement (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  biblio_id bigint not null references public.biblios(id) on delete cascade,
  type text not null check (type in ('view', 'click', 'favorite', 'reserve')),
  created_at timestamptz not null default now()
);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  author text,
  reason text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.circulation_rules (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('Admin', 'Librarian', 'Patron')),
  loan_period_days integer,
  borrow_limit integer,
  fine_amount_per_day numeric(10,2),
  renewal_limit integer,
  grace_period_days integer,
  max_fine_amount numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint circulation_rules_role_unique unique (role)
);

create table if not exists public.global_settings (
  id bigint primary key,
  maintenance_mode boolean not null default false,
  allow_self_registration boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint global_settings_singleton check (id = 1)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text,
  action text,
  details text,
  admin_id uuid references public.users(id) on delete set null,
  action_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.reading_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  biblio_id bigint not null references public.biblios(id) on delete cascade,
  borrowed_at timestamptz not null,
  returned_at timestamptz,
  created_at timestamptz not null default now()
);

-- ----------
-- Indexes
-- ----------

create index if not exists idx_users_role on public.users(role);

create index if not exists idx_biblios_title on public.biblios using gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(author, '')));
create index if not exists idx_items_biblio_id on public.items(biblio_id);
create index if not exists idx_items_status on public.items(status);

create index if not exists idx_loans_user_status on public.loans(user_id, status);
create index if not exists idx_loans_due_date on public.loans(due_date);
create index if not exists idx_loans_biblio_id on public.loans(biblio_id);

create index if not exists idx_fines_user_status on public.fines(user_id, status);
create index if not exists idx_fines_created_at on public.fines(created_at desc);

create index if not exists idx_holds_user_status on public.holds(user_id, status);
create index if not exists idx_holds_biblio_status on public.holds(biblio_id, status);

create index if not exists idx_engagement_user_created on public.engagement(user_id, created_at desc);
create index if not exists idx_engagement_biblio_type on public.engagement(biblio_id, type);

create index if not exists idx_suggestions_user_status on public.suggestions(user_id, status);
create index if not exists idx_suggestions_created_at on public.suggestions(created_at desc);

create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_admin_id on public.audit_logs(admin_id, created_at desc);
create index if not exists idx_audit_logs_action on public.audit_logs(action);

create index if not exists idx_reading_history_user on public.reading_history(user_id, borrowed_at desc);

-- ----------
-- Utility functions
-- ----------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where id = auth.uid() limit 1;
$$;

grant execute on function public.current_user_role() to authenticated;

-- ----------
-- Triggers
-- ----------

drop trigger if exists tr_biblios_updated_at on public.biblios;
create trigger tr_biblios_updated_at
before update on public.biblios
for each row execute function public.set_updated_at();

drop trigger if exists tr_items_updated_at on public.items;
create trigger tr_items_updated_at
before update on public.items
for each row execute function public.set_updated_at();

drop trigger if exists tr_loans_updated_at on public.loans;
create trigger tr_loans_updated_at
before update on public.loans
for each row execute function public.set_updated_at();

drop trigger if exists tr_fines_updated_at on public.fines;
create trigger tr_fines_updated_at
before update on public.fines
for each row execute function public.set_updated_at();

drop trigger if exists tr_holds_updated_at on public.holds;
create trigger tr_holds_updated_at
before update on public.holds
for each row execute function public.set_updated_at();

drop trigger if exists tr_suggestions_updated_at on public.suggestions;
create trigger tr_suggestions_updated_at
before update on public.suggestions
for each row execute function public.set_updated_at();

drop trigger if exists tr_circulation_rules_updated_at on public.circulation_rules;
create trigger tr_circulation_rules_updated_at
before update on public.circulation_rules
for each row execute function public.set_updated_at();

drop trigger if exists tr_global_settings_updated_at on public.global_settings;
create trigger tr_global_settings_updated_at
before update on public.global_settings
for each row execute function public.set_updated_at();

-- ----------
-- Seed defaults
-- ----------

insert into public.global_settings (id, maintenance_mode, allow_self_registration)
values (1, false, true)
on conflict (id) do nothing;

insert into public.circulation_rules (
  role,
  loan_period_days,
  borrow_limit,
  fine_amount_per_day,
  renewal_limit,
  grace_period_days,
  max_fine_amount
)
values
  ('Admin', 30, 20, 0.25, 5, 3, 50.00),
  ('Librarian', 30, 15, 0.25, 5, 3, 50.00),
  ('Patron', 14, 5, 0.25, 2, 2, 25.00)
on conflict (role) do nothing;

-- ----------
-- RLS enablement
-- ----------

alter table public.users enable row level security;
alter table public.biblios enable row level security;
alter table public.items enable row level security;
alter table public.loans enable row level security;
alter table public.fines enable row level security;
alter table public.holds enable row level security;
alter table public.engagement enable row level security;
alter table public.suggestions enable row level security;
alter table public.circulation_rules enable row level security;
alter table public.global_settings enable row level security;
alter table public.audit_logs enable row level security;
alter table public.reading_history enable row level security;

alter table public.users force row level security;
alter table public.biblios force row level security;
alter table public.items force row level security;
alter table public.loans force row level security;
alter table public.fines force row level security;
alter table public.holds force row level security;
alter table public.engagement force row level security;
alter table public.suggestions force row level security;
alter table public.circulation_rules force row level security;
alter table public.global_settings force row level security;
alter table public.audit_logs force row level security;
alter table public.reading_history force row level security;

-- ----------
-- Policies: users
-- ----------

drop policy if exists users_admin_all on public.users;
create policy users_admin_all
on public.users
for all
to authenticated
using (public.current_user_role() = 'Admin')
with check (public.current_user_role() = 'Admin');

drop policy if exists users_self_select on public.users;
create policy users_self_select
on public.users
for select
to authenticated
using (id = auth.uid());

drop policy if exists users_self_insert_patron on public.users;
create policy users_self_insert_patron
on public.users
for insert
to authenticated
with check (id = auth.uid() and role = 'Patron');

-- ----------
-- Policies: biblios
-- ----------

drop policy if exists biblios_read_authenticated on public.biblios;
create policy biblios_read_authenticated
on public.biblios
for select
to authenticated
using (true);

drop policy if exists biblios_write_staff on public.biblios;
create policy biblios_write_staff
on public.biblios
for all
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'))
with check (public.current_user_role() in ('Admin', 'Librarian'));

-- ----------
-- Policies: items
-- ----------

drop policy if exists items_read_authenticated on public.items;
create policy items_read_authenticated
on public.items
for select
to authenticated
using (true);

drop policy if exists items_write_staff on public.items;
create policy items_write_staff
on public.items
for all
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'))
with check (public.current_user_role() in ('Admin', 'Librarian'));

-- ----------
-- Policies: loans
-- ----------

drop policy if exists loans_read_owner_or_staff on public.loans;
create policy loans_read_owner_or_staff
on public.loans
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists loans_write_staff on public.loans;
create policy loans_write_staff
on public.loans
for all
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'))
with check (public.current_user_role() in ('Admin', 'Librarian'));

-- ----------
-- Policies: fines
-- ----------

drop policy if exists fines_read_owner_or_staff on public.fines;
create policy fines_read_owner_or_staff
on public.fines
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists fines_insert_staff on public.fines;
create policy fines_insert_staff
on public.fines
for insert
to authenticated
with check (public.current_user_role() in ('Admin', 'Librarian'));

drop policy if exists fines_update_staff on public.fines;
create policy fines_update_staff
on public.fines
for update
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'))
with check (public.current_user_role() in ('Admin', 'Librarian'));

drop policy if exists fines_update_own on public.fines;
create policy fines_update_own
on public.fines
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid() and status in ('Unpaid', 'Paid'));

drop policy if exists fines_delete_admin on public.fines;
create policy fines_delete_admin
on public.fines
for delete
to authenticated
using (public.current_user_role() = 'Admin');

-- ----------
-- Policies: holds
-- ----------

drop policy if exists holds_read_owner_or_staff on public.holds;
create policy holds_read_owner_or_staff
on public.holds
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists holds_insert_owner_or_staff on public.holds;
create policy holds_insert_owner_or_staff
on public.holds
for insert
to authenticated
with check (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists holds_update_owner_or_staff on public.holds;
create policy holds_update_owner_or_staff
on public.holds
for update
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
)
with check (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists holds_delete_staff on public.holds;
create policy holds_delete_staff
on public.holds
for delete
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'));

-- ----------
-- Policies: engagement
-- ----------

drop policy if exists engagement_read_owner_or_staff on public.engagement;
create policy engagement_read_owner_or_staff
on public.engagement
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists engagement_insert_owner_or_staff on public.engagement;
create policy engagement_insert_owner_or_staff
on public.engagement
for insert
to authenticated
with check (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists engagement_update_staff on public.engagement;
create policy engagement_update_staff
on public.engagement
for update
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'))
with check (public.current_user_role() in ('Admin', 'Librarian'));

drop policy if exists engagement_delete_staff on public.engagement;
create policy engagement_delete_staff
on public.engagement
for delete
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'));

-- ----------
-- Policies: suggestions
-- ----------

drop policy if exists suggestions_read_owner_or_staff on public.suggestions;
create policy suggestions_read_owner_or_staff
on public.suggestions
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists suggestions_insert_owner_or_staff on public.suggestions;
create policy suggestions_insert_owner_or_staff
on public.suggestions
for insert
to authenticated
with check (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists suggestions_update_owner_or_staff on public.suggestions;
create policy suggestions_update_owner_or_staff
on public.suggestions
for update
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
)
with check (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists suggestions_delete_admin on public.suggestions;
create policy suggestions_delete_admin
on public.suggestions
for delete
to authenticated
using (public.current_user_role() = 'Admin');

-- ----------
-- Policies: circulation_rules
-- ----------

drop policy if exists circulation_rules_read_authenticated on public.circulation_rules;
create policy circulation_rules_read_authenticated
on public.circulation_rules
for select
to authenticated
using (true);

drop policy if exists circulation_rules_write_admin on public.circulation_rules;
create policy circulation_rules_write_admin
on public.circulation_rules
for all
to authenticated
using (public.current_user_role() = 'Admin')
with check (public.current_user_role() = 'Admin');

-- ----------
-- Policies: global_settings
-- ----------

drop policy if exists global_settings_read_authenticated on public.global_settings;
create policy global_settings_read_authenticated
on public.global_settings
for select
to authenticated
using (true);

drop policy if exists global_settings_write_admin on public.global_settings;
create policy global_settings_write_admin
on public.global_settings
for all
to authenticated
using (public.current_user_role() = 'Admin')
with check (public.current_user_role() = 'Admin');

-- ----------
-- Policies: audit_logs
-- ----------

drop policy if exists audit_logs_read_admin_or_librarian on public.audit_logs;
create policy audit_logs_read_admin_or_librarian
on public.audit_logs
for select
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'));

drop policy if exists audit_logs_read_owner on public.audit_logs;
create policy audit_logs_read_owner
on public.audit_logs
for select
to authenticated
using (admin_id = auth.uid());

drop policy if exists audit_logs_insert_staff on public.audit_logs;
create policy audit_logs_insert_staff
on public.audit_logs
for insert
to authenticated
with check (public.current_user_role() in ('Admin', 'Librarian'));

drop policy if exists audit_logs_insert_owner on public.audit_logs;
create policy audit_logs_insert_owner
on public.audit_logs
for insert
to authenticated
with check (admin_id = auth.uid());

drop policy if exists audit_logs_delete_admin on public.audit_logs;
create policy audit_logs_delete_admin
on public.audit_logs
for delete
to authenticated
using (public.current_user_role() = 'Admin');

-- ----------
-- Policies: reading_history
-- ----------

drop policy if exists reading_history_read_owner_or_staff on public.reading_history;
create policy reading_history_read_owner_or_staff
on public.reading_history
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('Admin', 'Librarian')
);

drop policy if exists reading_history_write_staff on public.reading_history;
create policy reading_history_write_staff
on public.reading_history
for all
to authenticated
using (public.current_user_role() in ('Admin', 'Librarian'))
with check (public.current_user_role() in ('Admin', 'Librarian'));
